import { RouteInfo } from "./sidebar.metadata";

export const ROUTES: RouteInfo[] = [
    {
        path: "",
        title: "MENUITEMS.MAIN.TEXT",
        moduleName: "",
        icon: "",
        class: "",
        groupTitle: true,
        submenu: [],
    },
    {
        path: "",
        title: "MENUITEMS.HOME.TEXT",
        moduleName: "dashboard",
        icon: "monitor",
        class: "menu-toggle",
        groupTitle: false,
        submenu: [
            {
                path: "dashboard/main",
                title: "MENUITEMS.HOME.LIST.DASHBOARD1",
                moduleName: "dashboard",
                icon: "",
                class: "ml-menu",
                groupTitle: false,
                submenu: [],
            },
            // {
            //     path: "dashboard/dashboard2",
            //     title: "MENUITEMS.HOME.LIST.DASHBOARD2",
            //     moduleName: "dashboard",
            //     icon: "",
            //     class: "ml-menu",
            //     groupTitle: false,
            //     submenu: [],
            // },
            // {
            //     path: "dashboard/dashboard3",
            //     title: "MENUITEMS.HOME.LIST.DASHBOARD3",
            //     moduleName: "dashboard",
            //     icon: "",
            //     class: "ml-menu",
            //     groupTitle: false,
            //     submenu: [],
            // },
        ],
    },
    // {
    //     path: "",
    //     title: "Authentication",
    //     moduleName: "authentication",
    //     icon: "user-check",
    //     class: "menu-toggle",
    //     groupTitle: false,
    //     submenu: [
    //         {
    //             path: "/authentication/signin",
    //             title: "Sign In",
    //             moduleName: "authentication",
    //             icon: "",
    //             class: "ml-menu",
    //             groupTitle: false,
    //             submenu: [],
    //         },
    //         {
    //             path: "/authentication/signup",
    //             title: "Sign Up",
    //             moduleName: "authentication",
    //             icon: "",
    //             class: "ml-menu",
    //             groupTitle: false,
    //             submenu: [],
    //         },
    //         {
    //             path: "/authentication/forgot-password",
    //             title: "Forgot Password",
    //             moduleName: "authentication",
    //             icon: "",
    //             class: "ml-menu",
    //             groupTitle: false,
    //             submenu: [],
    //         },
    //         {
    //             path: "/authentication/locked",
    //             title: "Locked",
    //             moduleName: "authentication",
    //             icon: "",
    //             class: "ml-menu",
    //             groupTitle: false,
    //             submenu: [],
    //         },
    //         {
    //             path: "/authentication/page404",
    //             title: "404 - Not Found",
    //             moduleName: "authentication",
    //             icon: "",
    //             class: "ml-menu",
    //             groupTitle: false,
    //             submenu: [],
    //         },
    //         {
    //             path: "/authentication/page500",
    //             title: "500 - Server Error",
    //             moduleName: "authentication",
    //             icon: "",
    //             class: "ml-menu",
    //             groupTitle: false,
    //             submenu: [],
    //         },
    //     ],
    // },
    {
        path: "",
        title: "Departments",
        moduleName: "extra-pages",
        icon: "anchor",
        class: "menu-toggle",
        groupTitle: false,
        submenu: [
            // {
            //     path: "/extra-pages/blank",
            //     title: "Blank Page",
            //     moduleName: "extra-pages",
            //     icon: "",
            //     class: "ml-menu",
            //     groupTitle: false,
            //     submenu: [],
            // },
            {
                path: "/extra-pages/work-initiator",
                title: "Work Initiatior",
                moduleName: "extra-pages",
                icon: "",
                class: "ml-menu",
                groupTitle: false,
                submenu: [],
            },
            {
                path: "/extra-pages/work-receiver",
                title: "Work Receiver",
                moduleName: "extra-pages",
                icon: "",
                class: "ml-menu",
                groupTitle: false,
                submenu: [],
            },
            {
                path: "/extra-pages/area-in-charge",
                title: "Area In Charge(HOD)",
                moduleName: "extra-pages",
                icon: "",
                class: "ml-menu",
                groupTitle: false,
                submenu: [],
            },
            {
                path: "/extra-pages/maintenance",
                title: "Maintenance",
                moduleName: "extra-pages",
                icon: "",
                class: "ml-menu",
                groupTitle: false,
                submenu: [],
            },
            {
                path: "/extra-pages/security",
                title: "Security",
                moduleName: "extra-pages",
                icon: "",
                class: "ml-menu",
                groupTitle: false,
                submenu: [],
            },
            {
                path: "/extra-pages/safety-officer",
                title: "Safety Officer / EHS",
                moduleName: "extra-pages",
                icon: "",
                class: "ml-menu",
                groupTitle: false,
                submenu: [],
            },
            {
                path: "/extra-pages/factory-manager",
                title: "Factory Manager",
                moduleName: "extra-pages",
                icon: "",
                class: "ml-menu",
                groupTitle: false,
                submenu: [],
            },
            {
                path: "/extra-pages/divisional-head",
                title: "Divisional Head",
                moduleName: "extra-pages",
                icon: "",
                class: "ml-menu",
                groupTitle: false,
                submenu: [],
            },
        ],
    },
    {
        path: "",
        title: "Work Permit Form",
        moduleName: "multilevel",
        icon: "chevrons-down",
        class: "menu-toggle",
        groupTitle: false,
        submenu: [
            {
                path: "/multilevel/first1",
                title: "Raise Work Permit",
                moduleName: "multilevel",
                icon: "",
                class: "ml-menu",
                groupTitle: false,
                submenu: [],
            },
            // {
            //     path: "/",
            //     title: "Second",
            //     moduleName: "secondlevel",
            //     icon: "",
            //     class: "ml-sub-menu",
            //     groupTitle: false,
            //     submenu: [
            //         {
            //             path: "/multilevel/secondlevel/second1",
            //             title: "Second 1",
            //             moduleName: "secondlevel",
            //             icon: "",
            //             class: "ml-sub-sub-menu",
            //             groupTitle: false,
            //             submenu: [],
            //         },
            //         {
            //             path: "/multilevel/secondlevel/second2",
            //             title: "Second 2",
            //             moduleName: "secondlevel",
            //             icon: "",
            //             class: "ml-sub-sub-menu",
            //             groupTitle: false,
            //             submenu: [],
            //         },
            //     ],
            // },
            {
                path: "/multilevel/first3",
                title: "View All Forms",
                moduleName: "multilevel",
                icon: "",
                class: "ml-menu",
                groupTitle: false,
                submenu: [],
            },
        ],
    },
];
